name: cyrilbaldy
favicon: null
layout_spectrum: 0.553
typography_spectrum: 0.3773790462873876
title: 'whatever, precisely.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5b5148'
    - '#847d61'
    - '#b0b2a6'
    - '#0c0000'
    - '#bbd0c4'
  brandStrength: 0.07361442944966257
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
