name: cyrilbaldy
favicon: null
layout_spectrum: 0.553
typography_spectrum: 0.35733
title: 'whatever, precisely.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131414'
    - '#cbcbcb'
    - '#737979'
    - '#ff5500'
    - '#13a8ba'
  brandStrength: 0.07361442944966257
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
